basePath: /v1
definitions:
  httputil.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.Income:
    properties:
      id:
        type: string
      netIncome:
        type: string
      note:
        type: string
      submitDate:
        type: string
      totalIncome:
        type: string
      userId:
        type: string
      vat:
        type: string
      wht:
        type: string
    type: object
  models.IncomeReq:
    properties:
      note:
        type: string
      totalIncome:
        type: string
    type: object
  models.IncomeRes:
    properties:
      status:
        type: string
      submitDate:
        type: string
      user:
        $ref: '#/definitions/models.User'
        type: object
    type: object
  models.Login:
    properties:
      id:
        type: string
    type: object
  models.Token:
    properties:
      token:
        type: string
    type: object
  models.User:
    properties:
      bankAccountName:
        type: string
      bankAccountNumber:
        type: string
      corporateFlag:
        type: string
      email:
        type: string
      fullnameEn:
        type: string
      fullnameTh:
        type: string
      id:
        type: string
      thaiCitizenId:
        type: string
    type: object
host: http://worklog-dev.odds.team/api
info:
  contact: {}
  description: This is a sample server odds-worklog server.
  license: {}
  title: Odds-Worklog Example API
  version: "1.0"
paths:
  /api/income:
    post:
      consumes:
      - application/json
      description: Add Income
      parameters:
      - description: ' '
        in: body
        name: income
        required: true
        schema:
          $ref: '#/definitions/models.IncomeReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Income'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Add Income
      tags:
      - incomes
  /api/income/{id}:
    put:
      consumes:
      - application/json
      description: Update Income
      parameters:
      - description: ' '
        in: body
        name: income
        required: true
        schema:
          $ref: '#/definitions/models.IncomeReq'
          type: object
      - description: Income ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Income'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Update Income
      tags:
      - incomes
  /api/income/month/{id}:
    get:
      consumes:
      - application/json
      description: Get Income Of Current Month By User Id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Income'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Get Income Of Current Month By User Id
      tags:
      - incomes
  /api/income/status:
    get:
      consumes:
      - application/json
      description: Get Income Status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.IncomeRes'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Get Income Status
      tags:
      - incomes
  /login:
    post:
      consumes:
      - application/json
      description: Login get token
      parameters:
      - description: id is userId
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.Login'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Token'
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Login
      tags:
      - login
  /users:
    get:
      consumes:
      - application/json
      description: get user list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: List user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: id can empty
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Create User
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - multipart/form-data
      description: Delete User By Id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/models.User'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Delete User
      tags:
      - users
    patch:
      consumes:
      - multipart/form-data
      description: Delete Update Partial User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: id can empty
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Update Partial User
      tags:
      - users
    post:
      consumes:
      - multipart/form-data
      description: Get User By Id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
            type: object
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Get User By Id
      tags:
      - users
    put:
      consumes:
      - multipart/form-data
      description: Update User By Id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: id can empty
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: Update User By Id
      tags:
      - users
swagger: "2.0"
