version: "3"

services:
  api:
    container_name: "odds-worklog-api"
    build: .
    command: /app/api
    ports:
      - 8080:8080
    env_file:
      - dev.env
    depends_on:
      - "mongodb"
    networks:
      - odds_worklog_api
    restart: always

  friendslog:
    container_name: "odds-worklog-friendslog-subscriber"
    build: .
    command: /app/subscribe_friendslog
    env_file:
      - dev.env
    depends_on:
      - "mongodb"
      - "queue"
    networks:
      - odds_worklog_api
    restart: always

  mongodb:
    extends:
      file: ./docker-compose.local.yaml
      service: mongodb
    networks:
      - odds_worklog_api

  queue:
    extends:
      file: ./docker-compose.local.yaml
      service: queue

    networks:
      - odds_worklog_api

  keycloak:
    extends:
      file: ./docker-compose.local.yaml
      service: keycloak
    networks:
      - odds_worklog_api

volumes:
  mongodbdata_odds_worklog:

networks:
  odds_worklog_api:
