version: '3'
services:
  api:
    container_name: 'api.odds-worklog'
    build: './app'
    ports:
      - '8080:8080'
    volumes:
      - './app:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    container_name: 'mongodb'
    build: './mongodb'
    ports:
      - '27100:27017'