version: '3'
services:
  api:
    container_name: 'odds-worklog-api'
    build: './app'
    ports:
      - '8080:8080'
    volumes:
      - './app:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    container_name: 'odds-worklog-mongo'
    build: './mongodb'
    ports:
      - 27017:27017