version: '3'
services:
  api:
    container_name: 'odds-worklog-api'
    build: .
    command: /app/api 
    ports:
      - 8080:8080
    env_file:
      - dev.env
    depends_on:
      - 'mongodb'
    networks: 
      - odds_worklog_db
      - odds_worklog_rabbitmq
  mongodb:
    container_name: 'odds-worklog-mongo'
    image: 'mongo'
    volumes:
      - mongodbdata_odds_worklog:/data/db
    env_file:
      - dev.env
    expose:
      - '27017' 
    networks: 
      - odds_worklog_db
volumes:
  mongodbdata_odds_worklog:
networks: 
  odds_worklog_api:
  odds_worklog_db:
  odds_worklog_rabbitmq:
    external:
      name: odds_worklog_rabbitmq
