version: '3'
services:
  api:
    container_name: 'odds-worklog-api'
    build: .
    ports:
      - 8080:8080
    volumes:
      - '.:/go/src/app'
    depends_on:
      - 'mongodb'
  mongodb:
    container_name: 'odds-worklog-mongo'
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: odds_worklog_db 
    ports:
      - 27017:27017 