services:
  api:
    container_name: "odds-worklog-api"
    build: ../..
    command: /app/api
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - KEYCLOAK_SERVER_URL=https://keycloak_proxy
    depends_on:
      - "mongodb"
    networks:
      - odds_worklog_api
    restart: always

  friendslog:
    container_name: "odds-worklog-friendslog-subscriber"
    build: ../..
    command: /app/subscribe_friendslog
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=queue:5672
    depends_on:
      - "mongodb"
      - "queue"
    networks:
      - odds_worklog_api
    restart: always

  mongodb:
    extends:
      file: ./docker-compose.yaml
      service: mongodb
    networks:
      - odds_worklog_api

  queue:
    extends:
      file: ./docker-compose.yaml
      service: queue

    networks:
      - odds_worklog_api

  keycloak:
    extends:
      file: ./docker-compose.yaml
      service: keycloak
    networks:
      - odds_worklog_api

  keycloak_proxy:
    image: nginx:alpine
    volumes:
      - ../../deployment/ci/ssl/nginx-keycloak.conf:/etc/nginx/conf.d/default.conf
      - ../../deployment/ci/ssl:/etc/nginx/ssl
    ports:
      - "4443:443"
    networks:
      - odds_worklog_api
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  mongodbdata_odds_worklog:

networks:
  odds_worklog_api:
    external: true
