services:
  mongodb:
    extends:
      file: ../base/docker-compose.yaml
      service: mongodb
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  keycloak:
    extends:
      file: ../base/docker-compose.yaml
      service: keycloak
