services:
  api:
    extends:
      file: ../local/docker-compose.debug-ci.yaml
      service: api
    networks:
      - odds_worklog_api
  mongodb:
    extends:
      file: ../local/docker-compose.yaml
      service: mongodb
    networks:
      - odds_worklog_api

  keycloak:
    extends:
      file: ../local/docker-compose.yaml
      service: keycloak
    command: start-dev --import-realm --hostname-strict false --proxy-headers xforwarded
    networks:
      - odds_worklog_api

  keycloak_proxy:
    extends:
      file: ../local/docker-compose.debug-ci.yaml
      service: keycloak_proxy
    volumes:
      - ./ssl/nginx-keycloak.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl

volumes:
  mongodbdata_odds_worklog:

networks:
  odds_worklog_api:
    external: true
