services:
  api:
    extends:
      file: ../../docker-compose.yaml
      service: api
    environment:
      - KEYCLOAK_SERVER_URL=https://keycloak_proxy
    networks:
      - odds_worklog_api
  mongodb:
    extends:
      file: ../local/docker-compose.yaml
      service: mongodb
    networks:
      - odds_worklog_api

  keycloak:
    extends:
      file: ../local/docker-compose.yaml
      service: keycloak
    command: start-dev --import-realm --hostname-strict false --proxy-headers xforwarded
    networks:
      - odds_worklog_api

  keycloak_proxy:
    image: nginx:alpine
    volumes:
      - ./ssl/nginx-keycloak.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "4443:443"
    networks:
      - odds_worklog_api
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  mongodbdata_odds_worklog:

networks:
  odds_worklog_api:
    external: true
