on:
  push:
    branches: ["deployment/odds-cloud"]

name: CI/CD Project worklogAPI Develop (ODDS Cloud)

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and push it to ECR 
           docker build -t 844772501268.dkr.ecr.ap-southeast-1.amazonaws.com/api-worklog:dev-odds-cloud .
           docker tag 844772501268.dkr.ecr.ap-southeast-1.amazonaws.com/api-worklog:dev-odds-cloud 844772501268.dkr.ecr.ap-southeast-1.amazonaws.com/api-worklog:dev-odds-cloud
           docker push 844772501268.dkr.ecr.ap-southeast-1.amazonaws.com/api-worklog:dev-odds-cloud
  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull docker image
        id: pull-image
        run: |
          docker pull 844772501268.dkr.ecr.ap-southeast-1.amazonaws.com/api-worklog:dev-odds-cloud
          
      - name: Checkout for get docker compose file
        uses: actions/checkout@v2
        
      - name: copy docker compose file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.ODDS_CLOUD_DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.ODDS_CLOUD_DEV_PRIVATE_KEY}}
          source: "deployment/dev/docker-compose.yaml"
          target: "/home/ubuntu/worklog"

      - name: SSH Shell Command
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ubuntu/worklog
            docker compose down
            docker compose up -d
          host: ${{ vars.ODDS_CLOUD_DEV_HOST }}
          user: ubuntu
          key: ${{ secrets.ODDS_CLOUD_DEV_PRIVATE_KEY}}
