on:
  workflow_dispatch:

name: Reset Dev Odds cloud Data

jobs:
  build:
    name: Reset
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run reset Data
        id: reset-data
        run: |
          docker exec odds-worklog-mongo mkdir -p /fixture/data
          docker cp ./data odds-worklog-mongo:/fixture/data
          bash ./scripts/import_all_data
